language: python
sudo: false
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r test_requirements.txt
script:
  - flake8 src/
  - tox
notifications:
  email:
    - itconsense@gmail.com
