language: python
# for Python 3.7 *sigh*
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r test_requirements.txt
script:
  - flake8 src/
  - tox
notifications:
  email:
    - itconsense@gmail.com
